- metadata-app/src/components/Navigation/index.js
This fixes a bug where tab past nav step triggers step.
> Execute Nav step on <ENTER>

- metadata-app/src/api/index.js
- metadata-app/src/components/MetadataForm/index.js
- metadata-app/src/components/ResourceUpload/index.fixture.js
- metadata-app/src/components/ResourceUpload/index.js
- metadata-app/src/components/ResourceUpload/index.test.js
- metadata-app/src/components/ResourceUpload/validationSchema.js
- metadata-app/src/components/WrappedField/index.js
- metadata-app/src/css/custom.css
Includes:
- general UI for 'Resource Upload' component
- implementation for linking to data
Note, uploading a file doesn't work yet and will b delivered in a separate PR.
> Resource upload component with link to data implementation

- ckanext/dcat_usmetadata/templates/new-metadata.html
- requirements-freeze.txt
- requirements.txt
Don't do auth check as workaround for the bug.
> Access to new metadata form

- ckanext/dcat_usmetadata/fanstatic/custom.css
- ckanext/dcat_usmetadata/plugin.py
- ckanext/dcat_usmetadata/templates/organization/read.html
- cypress/integration/user-flow.spec.js
Note, this implementation requires changes in "datajson" extension in order to work in the "inventory" app.
TODO:
> "Add dataset" button should link to new metadata form

- .circleci/config.yml
- setup.py
Removed filter from CI config that was blocking the deploy job.
> Releasing a new version of the extension

- metadata-app/src/api/index.js
- metadata-app/src/api/index.test.js
- metadata-app/src/components/AdditionalMetadata/__snapshots__/index.test.js.snap
- metadata-app/src/components/AdditionalMetadata/index.js
> Fix: Release date field

- README.md
> Fix: Update README to explain unit test usage

- metadata-app/src/components/MetadataForm/__snapshots__/index.test.js.snap
- metadata-app/src/components/RequiredMetadata/__snapshots__/index.test.js.snap
- metadata-app/src/components/RequiredMetadata/publishers.json
Related issue: 
https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/498
> Udpate publisher dropdown

- metadata-app/src/components/MetadataForm/index.js
- metadata-app/src/components/ResourceUpload/__snapshots__/index.test.js.snap
- metadata-app/src/components/ResourceUpload/index.js
- setup.py
Demo:
~~https://www.awesomescreenshot.com/video/1526784?key=e3329b4875ea342719e393850077063d~~
Updated demo:
https://www.awesomescreenshot.com/video/1528197?key=89ed0e5fa98398e8451f3f497e0e6f33
> Disable submit buttons while file is uploading to the server

- README.md
https://github.com/gsa/ckanext-dcat_usmetadata/issues/93
Otherwise, the command hangs waiting for input.
> Use non-interactive unit test command

- metadata-app/src/components/ResourceUpload/index.js
> Fix: check() is not a function error in tests

- .circleci/config.yml
Running Python linting in the CI in a separate job.
> Run both JS and Python linting in the CI.

- cypress/integration/required-metadata.spec.js
- cypress/support/commands.js
- metadata-app/src/api/index.js
- metadata-app/src/api/index.test.js
- metadata-app/src/components/MetadataForm/__snapshots__/index.test.js.snap
- metadata-app/src/components/RequiredMetadata/__snapshots__/index.test.js.snap
- metadata-app/src/components/RequiredMetadata/defaultValues.js
- metadata-app/src/components/RequiredMetadata/index.js
- metadata-app/src/components/RequiredMetadata/validationLabels.js
- metadata-app/src/components/RequiredMetadata/validationSchema.js
- package.json
- yarn.lock
Related task:
https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/482
https://www.loom.com/share/09e700ef76f248e5bd8c591b09b11023
> Feature: Add modified field in required page

- metadata-app/src/api/index.js
- metadata-app/src/components/MetadataForm/__snapshots__/index.test.js.snap
- metadata-app/src/components/RequiredMetadata/__snapshots__/index.test.js.snap
- metadata-app/src/components/RequiredMetadata/index.js
- metadata-app/src/components/RequiredMetadata/validationLabels.js
- metadata-app/src/components/RequiredMetadata/validationSchema.js
> Update: Change modified date label to Update Frequency 

- cypress/integration/required-metadata.spec.js
- metadata-app/src/components/RequiredMetadata/index.js
Related issue:
https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/ckanext-dcat_usmetadata/109
Demo:
https://www.loom.com/share/88c064f21bab498480769a6baae6d6f8
> Feature: Pre-select organization in dropdown from an org page

- metadata-app/src/components/RequiredMetadata/index.js
Fix in validation error message of organization dropdown.
> Fix: validation error message for organization

- metadata-app/src/components/AdditionalMetadata/__snapshots__/index.test.js.snap
- metadata-app/src/components/MetadataForm/__snapshots__/index.test.js.snap
- metadata-app/src/components/RequiredMetadata/__snapshots__/index.test.js.snap
- metadata-app/src/components/RequiredMetadata/index.js
- metadata-app/src/components/ToolTip/index.fixture.js
- metadata-app/src/components/ToolTip/index.js
- metadata-app/src/components/ToolTip/index.test.js
- metadata-app/src/components/WrappedField/index.js
- metadata-app/src/css/custom.css
Related issue:
https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/508
Demo:
https://www.loom.com/share/a3c43591e4264f0485b0fde8271d6bf3
> Fix: Tool tip should close when you click outside it

- cypress/integration/user-flow.spec.js
- metadata-app/src/components/MetadataForm/__snapshots__/index.test.js.snap
- metadata-app/src/components/MetadataForm/index.js
- metadata-app/src/css/custom.css
Related issue:
https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/516
Demo:
https://www.loom.com/share/9a818c6c64f54565929ea383ff83ec22
> Feature: back to dashboard

- package.json
- react-scripts-config/webpack.config.js
This is related to https://github.com/GSA/datagov-ckan-multi/issues/390
> Change public/static to public/stat because of CKAN bug

- MANIFEST.in
This is related to https://github.com/gsa/datagov-ckan-multi/issues/390
> Update MANIFEST to include public/assets instead of public/static

- setup.py
This is related to https://github.com/GSA/datagov-ckan-multi/issues/390
> Bump version to 0.2.8

- cypress/integration/edit-dataset.spec.js
- metadata-app/src/api/index.js
Related issue:
https://github.com/GSA/datagov-ckan-multi/issues/547
Tasks done:
- Fix "other" option with custom value in "Data Dictionary Type" and "Data Publishing Frequency" dropdowns should be pre-populated as well
- N/A License field should be pre-populated if it is absent
- Write a new test for N/A License edge case
- Update edit tests for custom value edge cases in "Data Dictionary Type" and "Data Publishing Frequency"
> Bug: Fix edit dataset bugs 

- cypress/integration/resource-upload.spec.js
- cypress/support/commands.js
- metadata-app/src/components/Radio/index.js
- metadata-app/src/components/ResourceUpload/__snapshots__/index.test.js.snap
- metadata-app/src/components/ResourceUpload/index.js
Related issue:
https://github.com/GSA/datagov-ckan-multi/issues/524
This partially covers https://github.com/GSA/datagov-ckan-multi/issues/524, the rest remains last two radio options
Demo:
https://www.loom.com/share/6a78d83cab3f4eed9d2722103f0dd32f
> Feature: Convert file buttons in resource section into radio 

- Dockerfile
- bin/ci-build.bash
- package.json
- requirements-freeze.txt
- requirements.txt
pip 21 no longer support python 2
> Pin pip version for python 2

- cypress/integration/edit-dataset.spec.js
- metadata-app/src/components/ResourceUpload/__snapshots__/index.test.js.snap
- metadata-app/src/components/ResourceUpload/index.js
- package.json
- yarn.lock
Used `@cmsgov/design-system` provided `Dialogue` component to implement confirmation flow when deleting a resource on Resource Upload page.
Demo:
https://www.awesomescreenshot.com/video/2690534?key=fc13c82d30864b512dfb0c44e4400363
> Confirmation dialogue on resource delete

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- ckanext/dcat_usmetadata/templates/templates_2_8/new-metadata.html
- ckanext/dcat_usmetadata/templates/templates_new/new-metadata.html
- ckanext/dcat_usmetadata/tests/test_plugin.py
- requirements-py2.txt
- requirements.txt
- setup.py
Because the metadata app is not tracked by the main repo, special procedures need to be run to get the app bundled with the main code and published to PyPI.
> Publish extension to PyPI

- .github/workflows/deploy.yml
- Fixes syntax errors in the github action file.
- Also allow deploy to pypi to be run manually.
> Fix PyPI Deploy

- setup.py
> release 0.3.1

- .github/workflows/test.yml
- Makefile
- ckanext/dcat_usmetadata/fanstatic/webassets.yml
- ckanext/dcat_usmetadata/templates/templates_2_8/base.html
- ckanext/dcat_usmetadata/templates/templates_new/base.html
- cypress/integration/organization.spec.js
- docker-compose.cypress.yml
Related to https://github.com/GSA/data.gov/issues/3613
Fixes the webassets migration from PY2 to PY3.  References:
- https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions#web-assets-js-and-css
- https://docs.ckan.org/en/2.9/theming/webassets.html
> Remove Duplicate 'Add Dataset' Button

- .gitignore
- docker-compose.cypress.yml
- requirements.txt
remove git installs for any repos on pipi
bump version of cypress
> update version of ckantoolkit to mirror req from ckanext-harvest

- .github/workflows/test.yml
- ckanext/dcat_usmetadata/tests/test_plugin.py
Related to
- https://github.com/GSA/data.gov/issues/4113
- https://github.com/GSA/data.gov/issues/4121
Notable changes:
- https://github.com/GSA/ckanext-dcat_usmetadata/pull/302/commits/f97023983dc5d9ed13b085cb726c6302cc44c701
> Reference Reusable Workflows (as much as possible)

- ckanext/dcat_usmetadata/db_utils.py
- cypress/integration/resource-upload.spec.js
- cypress/integration/user-flow.spec.js
Related to
- https://github.com/GSA/data.gov/issues/4209
- #308 
- https://github.com/GSA/ckanext-usmetadata/pull/70
> Fix All Cypress Tests for CKAN 2.10

- ckanext/dcat_usmetadata/templates/new-metadata.html
- metadata-app/src/api/index.js
- package.json
- setup.py
- yarn.lock
Embed CKAN token in React DOM and then pass it as a header when invoking CKAN API. Required change for 2.10
Related to:
- https://github.com/GSA/data.gov/issues/4209
- https://github.com/GSA/ckanext-dcat_usmetadata/pull/308
> Pass CSRF token to API

- metadata-app/src/components/MetadataForm/index.jsx
- metadata-app/src/components/ToolTip/index.jsx
- package.json
- requirements.txt
- vite.config.js
- yarn.lock
in reference to [#4460](https://github.com/GSA/data.gov/issues/4460)
> Upgrade uswds to v3

- .github/workflows/test.yml
- cypress.json
- metadata-app/src/api/index.js
Reference: GSA/data.gov#5164
- Updates the Default Bureau and Program Codes for Update and Create calls
- `bureauCode`: 000:00
- `programCode`: 000:000
> Change Default `bureau`/`programCodes`

- ckanext/dcat_usmetadata/blueprint.py
- setup.py
For https://github.com/GSA/data.gov/issues/5234
```
check_access('package_update', context, data_dict)
```
> Check access
