- .circleci/config.yml
- README.md
- package.json
Includes:
* we now run unit tests in the CI prior to running e2e tests;
* we persist build files between jobs so that when running e2e tests, it uses latest builds no matter if developer has pushed it or not.
Also:
* prepared a script to ease running of e2e tests locally so we now can run `yarn e2e` from the root directory of the project;
* updated the README about it.
> CI improvements

- .circleci/config.yml
Otherwise, when we have a tagged commit in a branch it triggers deploy once. Then when it's merged to master, it tries to trigger deploy job again.
Example:
https://app.circleci.com/pipelines/github/GSA/ckanext-dcat_usmetadata/479/workflows/9cbe35ef-09da-4b43-b6ea-3270679dd2d3/jobs/1144
As you can see, deploy job failed with the following message:
> HTTPError: 400 Client Error: File already exists. See https://pypi.org/help/#file-name-reuse for more information. for url: https://upload.pypi.org/legacy/
> Run deploy job only on master branch

- metadata-app/src/api/index.js
- metadata-app/src/api/index.test.js
Related issue:
https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/ckanext-dcat_usmetadata/97
- Changed decode->deserialize (encode->serialize) funcitons to have more appropriate names.
- Every function which sends a payload it's being encoded (URI encoding)
> Fix: bug in the encoding of the payload being submitted

- MANIFEST.in
- setup.py
Fixed path to static files in the `MANIFEST.in` as it was wrongly specified with `-` instead of `_`. Probably, the project structure was different in the beginning so it was leftover since then.
> PyPI package installation

- metadata-app/package.json
- metadata-app/yarn.lock
Alert:
https://github.com/GSA/ckanext-dcat_usmetadata/network/alerts
> Fix security vulnerabilities in packages

- ckanext/dcat_usmetadata/templates/new-metadata.html
Chunk css file should be loaded after main css in order to let the classes override the necessary styles.
> Fix: Load main css file first before chunk css

- cypress/integration/required-metadata.spec.js
- metadata-app/src/components/AutocompleteTags/index.js
Related issue:
https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-deploy/2297
https://www.loom.com/share/0d7a8ec90d1d4917b6f13b2bf546e4bf
> Fix: Allow to add new tag on blur without hiting enter or tab

- setup.py
Create release 0.2.7. This  changes public/static dir for resources to public/assets. This is related to https://github.com/gsa/datagov-ckan-multi/issues/390
> Create release version 0.2.7

- cypress/integration/resource-upload.spec.js
- cypress/support/commands.js
- metadata-app/src/components/MetadataForm/__snapshots__/index.test.js.snap
- metadata-app/src/components/MetadataForm/index.js
- metadata-app/src/components/RequiredMetadata/__snapshots__/index.test.js.snap
- metadata-app/src/components/RequiredMetadata/index.js
- metadata-app/src/components/ResourceUpload/__snapshots__/index.test.js.snap
- metadata-app/src/components/ResourceUpload/index.js
- metadata-app/src/css/custom.css
Related issue: 
https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/502
It's not completely done, only the FE part such as:
1. Listing the already existing resources
2. Showing mock Edit and Delete buttons
3. Moving "Save..." message to top
4. Long names are truncated
5. Cypress test is written
Demo:
> Feature: List resources on edit mode in Resource Upload section

- cypress/integration/additional-metadata.spec.js
- cypress/support/commands.js
- metadata-app/src/components/AdditionalMetadata/index.js
- metadata-app/src/components/MetadataForm/index.js
When editing a dataset, in additional metadata page, we have parent dataset value as an id which is confusing:
* not human readable;
* not consistent with what a user has selected when creating a dataset (dataset title).
This PR fixes the UX so that user sees a parent dataset title instead of id.
> Display parent dataset title instead of random id

- metadata-app/src/api/index.js
Don't pass null values when posting form data with `resource_update` API call. It causes unexpected behaviour from the CKAN API raising validation error. Specifically, it fails with 'wrong date format' error for 'last_modified' attribute. The challenge is that we couldn't reproduce it within local inventory instance so we needed to develop/debug against live sandbox (you can do it by running React app locally and pointing to sandbox).
> Bug fix in sandbox when re-uploading a file.

- package.json
- yarn.lock
These are fixes that Dependabot can't update to a non-vulnerable version:
https://github.com/GSA/ckanext-dcat_usmetadata/security/dependabot
> Fix potential security vulnerabilities in the dependencies

- ckanext/dcat_usmetadata/cli.py
- ckanext/dcat_usmetadata/publishers.test.csv
- cypress/integration/publishers.spec.js
- seed.sh
- setup.py
- yarn.lock
Usage:
`paster --plugin=ckanext-dcat_usmetadata publishers-import path-to-csv -c /etc/ckan/production.ini`
This PR adds a new CLI command for importing publishers into CKAN db (organization's extra metadata).
The CSV data should have the following format:
```
organization,publisher,publisher_1,publisher_2,publisher_3,publisher_4,publisher_5
agricultural-marketing-service-department-of-agriculture,Department of Agriculture,Agricultural Marketing Service,,,,
ars-usda-gov,Department of Agriculture,Agricultural Research Service,,,,
aphis-usda-gov,Department of Agriculture,Animal and Plant Health Inspection Service,,,,
risk-management-agency-department-of-agriculture,Department of Agriculture,Departmental Management,,,,
usda-gov,Department of Agriculture,Office of Chief Information Officer,,,, …
```
> A new paster command for importing publishers

- ckanext/dcat_usmetadata/cli.py
- setup.py
Fixed issue GSA/datagov-deploy#3175 that `sub-agencies` is lost when publishers-import is run.
> Fix publishers import

- cypress/support/commands.js
- metadata-app/src/components/AdditionalMetadata/__snapshots__/index.test.js.snap
- metadata-app/src/components/AdditionalMetadata/publishingFrequencyList.json
R/P7D or R/P1W?
data.json expects R/P1W.
https://github.com/GSA/ckanext-datajson/blob/4ca1ca31cfcc23d6610c13693049fcfc83696d08/ckanext/datajson/datajsonvalidator.py#L64
R/P1W is official
https://resources.data.gov/schemas/dcat-us/v1.1/iso8601_guidance/#accrualperiodicity
> use R/P1W for weekly accrualPeriodicity

- MANIFEST.in
- setup.py
Related to https://github.com/GSA/data.gov/issues/3613
`webassets.yml` was missing from the release.
> Fix pypi release

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- README.md
Related to https://github.com/GSA/data.gov/issues/3414
Optimize the publish action to only use the required tools.
Successful Run: https://github.com/GSA/ckanext-dcat_usmetadata/runs/7283030060?check_suite_focus=true
> Dev-requirements are NOT necessary for PyPI release

- .github/workflows/deploy.yml
Related to
- https://github.com/GSA/inventory-app/pull/584
- https://github.com/GSA/ckanext-dcat_usmetadata/pull/306
- https://github.com/GSA/data.gov/issues/4262
> Pypi build needs to be pinned to node 16

- README.md
- metadata-app/src/api/index.js
- setup.py
- Bumps Pypi version to match online
- Check CSRF token present before passing in content property
> Update pypi version & make jest tests pass

- setup.py
Reference to PR: https://github.com/GSA/ckanext-dcat_usmetadata/pull/337
This PR is meant to bump the version number so that we can publish the changes introduced in the above PR to pypi.
> Bumps The Version Number to 0.6.2
